### ISSUE TITLE
Tip: Avoid committing .pyc files

### ISSUE THREAD

**Issue by bigfatnoob** [diksha/fss16noobs#1]
<img width="1097" alt="screen shot 2016-08-26 at 10 46 34 pm" src="https://cloud.githubusercontent.com/assets/5582924/18024711/13bb5756-6bdf-11e6-98f2-c7e279f11409.png">
- You can either use `sys.dont_write_bytecode = True` or
- add `*.pyc` in `.gitignore` file

**Comment by shahrajat** [comment]
Add a new .gitignore file. Thanks for the suggestion!
